Dev sqlalchemy
mtalimanchuk/e-xercise pull request #4
Opened 2019-06-28 00:01 UTC by derstolz

2019-06-28 15:23 UTC, mtalimanchuk requested changes
Please sort imports:
1. Standard imports (like os, logging, etc.)

2. 3rd party imports (like flask or any other pip-installed lib)

3. Local modules imports
Following alphabetical order

Also, put `jsonify` next to other `from flask` imports

2019-06-28 22:48 UTC, derstolz commented on app.py
> -    parser.add_argument('-p', '--port', dest='port', default=5000,
it turns out that those cli properties can override flask cli properties, so i decided to remove them

2019-06-29 13:32 UTC, mtalimanchuk reviewed
Awesome. Muchas gracias!

2019-06-29 13:33 UTC, mtalimanchuk approved these changes

2019-06-29 13:33 UTC, merged